### ISSUE TITLE
部署确认

### ISSUE THREAD

**Issue by Wx428285766** [sunzsh/internal-chat#8]
部署完成访问提示 需要升级
![1](https://github.com/user-attachments/assets/7919d3c0-608d-476e-9529-fdd5d4f7cb81)

**Comment by sunzsh** [comment]
这访问的是服务端，服务端不能用来直接访问，服务端只是用来给www建立websocket用的，你需要再单独部署客户端 `www`

**Comment by Wx428285766** [comment]
> 这访问的是服务端，服务端不能用来直接访问，服务端只是用来给www建立websocket用的，你需要再单独部署客户端 `www`

我以为客户端可以不安装任何东西呢
